### PR TITLE
An error occurs when conekta refuse connection or internet fails

### PR DESCRIPTION
**Pull request by fdorantesm**
modified:    conekta.js
	modified:    locales.json

Node breaks when statusCode is not 200 or 201, added validation to send an error with 503 statusCode with a string locale message.

### CODE REVIEW

**Comment by WCLab** [comment]
Yesterday we have this problem in production with php too, please accept and fix that error,

**Comment by fdorantesm** [comment]
Do you have some comment about this request?

**Comment by KarlaRobinson** [comment]
@fdorantesm Gracias por encontrar este bug. El equipo de ingeniería esta revisando este PR, y un fix del bug se lanzará en la próxima versión 👍

**Comment by KarlaRobinson** [comment]
@fdorantesm We had to decline this pull request because it does not follow our code standard.

However, a fix has been implemented!

Here you can see the commit added to address this issue you discovered: https://github.com/conekta/conekta-node/commit/5c755f97104452f37917c101adfe3d254744910a

**Pull request closed without merging**
